<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">

  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>TrustPatrick — XML Sitemap</title>
        <style>
          * { box-sizing: border-box; margin: 0; padding: 0; font-family: 'Source Sans Pro', system-ui, sans-serif; }
          body {
            font-family: 'Source Sans Pro', system-ui, sans-serif;
            background: #f0f4f8;
            color: #001b33;
          }
          header {
            background: #001b33;
            color: #fff;
            padding: 24px 32px;
          }
          header h1 { font-size: 22px; font-weight: 700; letter-spacing: 0.02em; }
          header p  { font-size: 13px; color: #a8c4d8; margin-top: 6px; }
          .stats {
            display: flex;
            gap: 24px;
            background: #002d54;
            padding: 14px 32px;
            flex-wrap: wrap;
          }
          .stat { color: #e8f1f8; font-size: 13px; }
          .stat strong { color: #fff; font-size: 18px; display: block; }
          main { max-width: 1100px; margin: 32px auto; padding: 0 16px; }
          table {
            width: 100%;
            border-collapse: collapse;
            background: #fff;
            border-radius: 10px;
            overflow: hidden;
            box-shadow: 0 2px 8px rgba(0,27,51,0.08);
          }
          thead tr { background: #001b33; color: #fff; }
          thead th {
            padding: 12px 16px;
            text-align: left;
            font-size: 12px;
            font-weight: 600;
            letter-spacing: 0.06em;
            text-transform: uppercase;
          }
          tbody tr:nth-child(even) { background: #f5f9fc; }
          tbody tr:hover { background: #e8f1f8; }
          tbody td {
            padding: 10px 16px;
            font-size: 13px;
            border-bottom: 1px solid #e0eaf2;
            vertical-align: middle;
          }
          tbody td:first-child { width: 55%; }
          a { color: #1a5a8a; text-decoration: none; word-break: break-all; }
          a:hover { text-decoration: underline; }
          .badge {
            display: inline-block;
            padding: 2px 8px;
            border-radius: 99px;
            font-size: 11px;
            font-weight: 600;
          }
          .p-high   { background: #001b33; color: #fff; }
          .p-mid    { background: #002d54; color: #fff; }
          .p-low    { background: #e8f1f8; color: #001b33; }
          .freq     { color: #1a5a8a; font-size: 12px; }
          footer {
            text-align: center;
            padding: 24px;
            font-size: 12px;
            color: #6b8fa8;
          }
        </style>
      </head>
      <body>
        <header>
          <h1>TrustPatrick — XML Sitemap</h1>
         
        </header>

        <div class="stats">
          <div class="stat">
            <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong>
            Total URLs
          </div>
          <div class="stat">
            <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url[sitemap:priority='1.0'])"/></strong>
            Priority 1.0
          </div>
          <div class="stat">
            <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url[sitemap:priority='0.8'])"/></strong>
            Priority 0.8
          </div>
          <div class="stat">
            <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url[sitemap:changefreq='weekly'])"/></strong>
            Updated Weekly
          </div>
        </div>

        <main>
          <table>
            <thead>
              <tr>
                <th>URL</th>
                <th>Last Modified</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="sitemap:urlset/sitemap:url">
                <tr>
                  <td>
                    <a href="{sitemap:loc}" target="_blank" rel="noopener">
                      <xsl:value-of select="sitemap:loc"/>
                    </a>
                  </td>
                  <td><xsl:value-of select="sitemap:lastmod"/></td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
        </main>

        <footer>
          Generated by TrustPatrick · <a href="https://www.sitemaps.org" target="_blank" rel="noopener">Sitemap Protocol 0.9</a>
        </footer>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
